#!/bin/sh

echo "ArgoCD:"
echo "admin"
export KUBECONFIG=./metal/kubeconfig.yaml
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d && echo ""
echo "-----"
echo "Grafana"
kubectl -n monitoring-system get secret monitoring-system-grafana -o jsonpath='{.data.admin-user}' | base64 -d && echo ""
kubectl -n monitoring-system get secret monitoring-system-grafana -o jsonpath='{.data.admin-password}' | base64 -d && echo ""

echo "-----"
echo "Gitea"
kubectl -n gitea get secret gitea-admin-secret -o jsonpath='{.data.username}' | base64 -d && echo ""
kubectl -n gitea get secret gitea-admin-secret -o jsonpath='{.data.password}' | base64 -d && echo ""
